/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.mavenproject2;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author ASUS
 */
public class coffeedesign extends javax.swing.JFrame {

    /**
     * Creates new form coffeedesign
     */
    public coffeedesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        HoneyI = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        CL = new javax.swing.JButton();
        EI2 = new javax.swing.JCheckBox();
        CLICK = new javax.swing.JButton();
        EF3 = new javax.swing.JCheckBox();
        AH1 = new javax.swing.JCheckBox();
        AI2 = new javax.swing.JCheckBox();
        LH1 = new javax.swing.JCheckBox();
        LI2 = new javax.swing.JCheckBox();
        LF3 = new javax.swing.JCheckBox();
        CH1 = new javax.swing.JCheckBox();
        EH1 = new javax.swing.JCheckBox();
        CI2 = new javax.swing.JCheckBox();
        CF3 = new javax.swing.JCheckBox();
        GH1 = new javax.swing.JCheckBox();
        GI2 = new javax.swing.JCheckBox();
        GF3 = new javax.swing.JCheckBox();
        TH1 = new javax.swing.JCheckBox();
        TI2 = new javax.swing.JCheckBox();
        TF3 = new javax.swing.JCheckBox();
        COH1 = new javax.swing.JCheckBox();
        COI2 = new javax.swing.JCheckBox();
        COF3 = new javax.swing.JCheckBox();
        MI2 = new javax.swing.JCheckBox();
        MF3 = new javax.swing.JCheckBox();
        MTI2 = new javax.swing.JCheckBox();
        MTF3 = new javax.swing.JCheckBox();
        LTI2 = new javax.swing.JCheckBox();
        LTF3 = new javax.swing.JCheckBox();
        MIH1 = new javax.swing.JCheckBox();
        MH1 = new javax.swing.JCheckBox();
        MII2 = new javax.swing.JCheckBox();
        MIF3 = new javax.swing.JCheckBox();
        NH1 = new javax.swing.JCheckBox();
        NI2 = new javax.swing.JCheckBox();
        NF3 = new javax.swing.JCheckBox();
        NTH1 = new javax.swing.JCheckBox();
        NTI2 = new javax.swing.JCheckBox();
        IF3 = new javax.swing.JCheckBox();
        NTF3 = new javax.swing.JCheckBox();
        RI2 = new javax.swing.JCheckBox();
        HI2 = new javax.swing.JCheckBox();
        Total = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        zxx = new javax.swing.JScrollPane();
        Zshow = new javax.swing.JTextPane();
        re = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFocusCycleRoot(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 280, 110));

        jLabel13.setFont(new java.awt.Font("Comic Sans MS", 3, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 0, 0));
        jLabel13.setText("Menu");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 70, -1));

        jLabel14.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 102));
        jLabel14.setText("milk");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel15.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 102));
        jLabel15.setText("Americano");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 102));
        jLabel17.setText("Esspresso");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel18.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 102));
        jLabel18.setText("Latte");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jLabel19.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 102));
        jLabel19.setText("Cappuccino");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel20.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 102));
        jLabel20.setText("Green Tae");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jLabel21.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 102));
        jLabel21.setText("Thai Tae");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, -1, -1));

        jLabel16.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 102));
        jLabel16.setText("milkTea");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, -1, -1));

        jLabel22.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 102));
        jLabel22.setText("ltalian Soda ");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, -1, 20));

        jLabel23.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 102));
        jLabel23.setText("CoCoa");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, -1, -1));

        jLabel24.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 102));
        jLabel24.setText("LemonTea");
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, -1, -1));

        jLabel25.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 102));
        jLabel25.setText("milo");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 50, -1));

        jLabel26.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 102));
        jLabel26.setText("Nestcafe");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        HoneyI.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        HoneyI.setForeground(new java.awt.Color(255, 255, 102));
        HoneyI.setText("Honey lime Soda");
        getContentPane().add(HoneyI, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 430, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 102));
        jLabel1.setText(" Red lime Soda");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 360, -1, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 102));
        jLabel2.setText("(Cantaloupe.Strawberry.Apple.BlueHawai)");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, 30));

        jLabel28.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 102));
        jLabel28.setText("NestcaTea");
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, -1, -1));

        jLabel29.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 102));
        jLabel29.setText("Red lime Soda");
        getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 51));
        jLabel3.setText("Hot");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 51));
        jLabel4.setText("Ice");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 51));
        jLabel5.setText("Frappe");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, -1));

        jLabel30.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 0, 51));
        jLabel30.setText("Hot");
        getContentPane().add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        jLabel31.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 0, 51));
        jLabel31.setText("Ice");
        getContentPane().add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, -1, -1));

        jLabel32.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 0, 51));
        jLabel32.setText("Frappe");
        getContentPane().add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, -1, -1));

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("Menu");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 40, -1));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 40, 20));

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 51, 255));
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 70, -1, -1));

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, -1, -1));

        CL.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        CL.setForeground(new java.awt.Color(153, 0, 204));
        CL.setText("Clear");
        CL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLActionPerformed(evt);
            }
        });
        getContentPane().add(CL, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 400, 80, -1));

        EI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        EI2.setText("45");
        getContentPane().add(EI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 40, 20));

        CLICK.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        CLICK.setText("OK");
        CLICK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLICKActionPerformed(evt);
            }
        });
        getContentPane().add(CLICK, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 490, 110, 30));

        EF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        EF3.setText("50");
        getContentPane().add(EF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 40, 20));

        AH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        AH1.setText("35");
        getContentPane().add(AH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 40, 20));

        AI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        AI2.setText("45");
        getContentPane().add(AI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 40, 20));

        LH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        LH1.setText("35");
        getContentPane().add(LH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 40, 20));

        LI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        LI2.setText("45");
        getContentPane().add(LI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 40, 20));

        LF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        LF3.setText("50");
        getContentPane().add(LF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 40, 20));

        CH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        CH1.setText("35");
        getContentPane().add(CH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 40, 20));

        EH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        EH1.setText("35");
        EH1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EH1ActionPerformed(evt);
            }
        });
        getContentPane().add(EH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 40, 20));

        CI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        CI2.setText("45");
        getContentPane().add(CI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 40, 20));

        CF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        CF3.setText("50");
        getContentPane().add(CF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 40, 20));

        GH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        GH1.setText("20");
        getContentPane().add(GH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 250, 40, 20));

        GI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        GI2.setText("25");
        getContentPane().add(GI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, 40, 20));

        GF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        GF3.setText("30");
        getContentPane().add(GF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 40, 20));

        TH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        TH1.setText("20");
        getContentPane().add(TH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 40, 20));

        TI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        TI2.setText("25");
        getContentPane().add(TI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, 40, 20));

        TF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        TF3.setText("30");
        getContentPane().add(TF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 40, 20));

        COH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        COH1.setText("20");
        getContentPane().add(COH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 330, 40, 20));

        COI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        COI2.setText("25");
        getContentPane().add(COI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 40, 20));

        COF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        COF3.setText("30");
        getContentPane().add(COF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 40, 20));

        MI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MI2.setText("25");
        getContentPane().add(MI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 40, 20));

        MF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MF3.setText("30");
        getContentPane().add(MF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 100, 40, 20));

        MTI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MTI2.setText("20");
        MTI2.setActionCommand("25");
        getContentPane().add(MTI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 40, 20));

        MTF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MTF3.setText("30");
        getContentPane().add(MTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, 40, 20));

        LTI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        LTI2.setText("20");
        LTI2.setActionCommand("25");
        getContentPane().add(LTI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 40, 20));

        LTF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        LTF3.setText("30");
        getContentPane().add(LTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 180, 40, 20));

        MIH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MIH1.setText("20");
        getContentPane().add(MIH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 40, 20));

        MH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MH1.setText("20");
        getContentPane().add(MH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 40, 20));

        MII2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MII2.setText("20");
        MII2.setActionCommand("25");
        getContentPane().add(MII2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 40, 20));

        MIF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        MIF3.setText("30");
        getContentPane().add(MIF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 220, 40, 20));

        NH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        NH1.setText("20");
        getContentPane().add(NH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 260, 40, 20));

        NI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        NI2.setText("20");
        NI2.setActionCommand("25");
        getContentPane().add(NI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 260, 40, 20));

        NF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        NF3.setText("30");
        getContentPane().add(NF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 260, 40, 20));

        NTH1.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        NTH1.setText("20");
        getContentPane().add(NTH1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 40, 20));

        NTI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        NTI2.setText("25");
        getContentPane().add(NTI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 40, 20));

        IF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        IF3.setText("25");
        getContentPane().add(IF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 330, 40, 20));

        NTF3.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        NTF3.setText("30");
        getContentPane().add(NTF3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, 40, 20));

        RI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        RI2.setText("25");
        getContentPane().add(RI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 40, 20));

        HI2.setFont(new java.awt.Font("Comic Sans MS", 3, 10)); // NOI18N
        HI2.setText("25");
        getContentPane().add(HI2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 430, 40, 20));

        Total.setFont(new java.awt.Font("Comic Sans MS", 3, 14)); // NOI18N
        getContentPane().add(Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 360, 50, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("฿");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 360, 80, 20));

        zxx.setViewportView(Zshow);

        getContentPane().add(zxx, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 100, 240, 250));

        re.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        re.setForeground(new java.awt.Color(153, 0, 204));
        re.setText("Receipt");
        re.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reActionPerformed(evt);
            }
        });
        getContentPane().add(re, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 400, 100, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLActionPerformed
     Zshow.setText ("");
     Total.setText ("");// TODO add your handling code here:
    }//GEN-LAST:event_CLActionPerformed

    private void CLICKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLICKActionPerformed
        Date date = new Date();
        int money = 0;
        String Mn = "";
        if(EH1.isSelected() == true){
        money = money+35;
        Mn +="   Esspresso                          35 ฿ " ;
        
        }
        if(EI2.isSelected() == true){
        money = money+45;
        Mn +="   Esspresso                          45 ฿ ";
        }
        if(EF3.isSelected() == true){
        money = money+50;
        Mn +="   Esspresso                          50 ฿ ";
        }
        if(AH1.isSelected() == true){
        money = money+35;
        Mn +="   Americano                          35 ฿ ";
        }
        if(AI2.isSelected() == true){
        money = money+45;
        Mn +="   Americano                          45 ฿ ";
        }
        if(LH1.isSelected() == true){
        money = money+35;
        Mn +="   Latte                              35 ฿ ";
        }
        if(LI2.isSelected() == true){
        money = money+45;
        Mn +="   Latte                              45 ฿ ";
        }
        if(LF3.isSelected() == true){
        money = money+50;
        Mn +="   Latte                              50 ฿ ";
        }
        if(CH1.isSelected() == true){
        money = money+35;
        Mn +="   Cappuccino                         35 ฿ ";
        }
        if(CI2.isSelected() == true){
        money = money+45;
        Mn +="   Cappuccino                         45 ฿ ";
        }
        if(CF3.isSelected() == true){
        money = money+50;
        Mn +="   Cappuccino                         50 ฿ ";
        }
        if(GH1.isSelected() == true){
        money = money+20;
        Mn +="   GreenTea                           20 ฿ ";
        }
        if(GI2.isSelected() == true){
        money = money+25;
        Mn +="   GreenTea                           25 ฿ ";
        }
        if(GF3.isSelected() == true){
        money = money+30;
        Mn +="   GreenTea                           30 ฿ ";
        }
        if(TH1.isSelected() == true){
        money = money+20;
        Mn +="   ThaiTea                            20 ฿ ";
        }
        if(TI2.isSelected() == true){
        money = money+25;
        Mn +="   ThaiTea                            25 ฿ ";
        }
        if(TF3.isSelected() == true){
        money = money+30;
        Mn +="   ThaiTea                            30 ฿ ";
        }
        if(COH1.isSelected() == true){
        money = money+20;
        Mn +="   CoCoa                              20 ฿ ";
        }
        if(COI2.isSelected() == true){
        money = money+25;
        Mn +="   CoCoa                              25 ฿ ";
        }
        if(COF3.isSelected() == true){
        money = money+30;
        Mn +="   CoCoa                              30 ฿ ";
        }
        if(MH1.isSelected() == true){
        money = money+20;
        Mn +="   Milk                               20 ฿ ";
        }
        if(MI2.isSelected() == true){
        money = money+25;
        Mn +="   Milk                               25 ฿ ";
        }
        if(MF3.isSelected() == true){
        money = money+30;
        Mn +="   Milk                               30 ฿ ";
        }
        if(MTI2.isSelected() == true){
        money = money+25;
        Mn +="   MilkTea                            25 ฿ ";
        }
        if(MTF3.isSelected() == true){
        money = money+30;
        Mn +="   MilkTea                            30 ฿ ";
        }
        if(LTI2.isSelected() == true){
        money = money+25;
        Mn +="   LemonTea                           25 ฿ ";
        }
        if(LTF3.isSelected() == true){
        money = money+30;
        Mn +="   LemonTea                           30 ฿ ";
        }
        if(MIH1.isSelected() == true){
        money = money+20;
        Mn +="   Milo                               20 ฿ ";
        }
        if(MII2.isSelected() == true){
        money = money+25;
        Mn +="   Milo                               25 ฿ ";
        }
        if(MIF3.isSelected() == true){
        money = money+30;
        Mn +="   Milo                               30 ฿ ";
        }
        if(NH1.isSelected() == true){
        money = money+20;
        Mn +="   Nestcafe                           20 ฿ ";
        }
        if(NI2.isSelected() == true){
        money = money+25;
        Mn +="   Nestcafe                           25 ฿ ";
        }
        if(NF3.isSelected() == true){
        money = money+30;
        Mn +="   Nestcafe                           30 ฿ ";
        }
        if(NTH1.isSelected() == true){
        money = money+20;
        Mn +="   NestcafeTea                        20 ฿ ";
        }
        if(NTI2.isSelected() == true){
        money = money+25;
        Mn +="   NestcafeTea                        25 ฿ ";
        }
        if(NTF3.isSelected() == true){
        money = money+30;
        Mn +="   NestcafeTea                        30 ฿ ";
        }
        if(IF3.isSelected() == true){
        money = money+25;
        Mn +="   Italian Soda                       25 ฿ ";
        }
        if(RI2.isSelected() == true){
        money = money+25;
        Mn +="   Red lime Soda                      25 ฿ ";
        }
        if(HI2.isSelected() == true){
        money = money+25;
        Mn +="   Honey lime Soda                    25 ฿ ";
        }
       
        Zshow.setText("CAFFEE Cafe"+ "Wellcome"+"\t\n\t\n"+Mn+"Total :" +money + "฿" +"\t\n\t\n"+"Date :" + date.toString());
        
        Total.setText(String.valueOf(money));
        

// TODO add your handling code here:
    }//GEN-LAST:event_CLICKActionPerformed

    private void EH1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EH1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EH1ActionPerformed

    private void reActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reActionPerformed
        String path = "C:\\Users\\ASUS\\Documents\\NetBeansProjects";
        File file = new  File(path);
        FileWriter writer;
            try {
                writer = new FileWriter(file,true);
                writer.write (Zshow.getText());
                writer.close();
                
                System.out.println("Write success!");
            } 
            catch (IOException ex) {
                ex.printStackTrace();
            Logger.getLogger(coffeedesign.class.getName()).log(Level.SEVERE, null, ex);
        }// TODO add your handling code here:
    }//GEN-LAST:event_reActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(coffeedesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(coffeedesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(coffeedesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(coffeedesign.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new coffeedesign().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AH1;
    private javax.swing.JCheckBox AI2;
    private javax.swing.JCheckBox CF3;
    private javax.swing.JCheckBox CH1;
    private javax.swing.JCheckBox CI2;
    private javax.swing.JButton CL;
    private javax.swing.JButton CLICK;
    private javax.swing.JCheckBox COF3;
    private javax.swing.JCheckBox COH1;
    private javax.swing.JCheckBox COI2;
    private javax.swing.JCheckBox EF3;
    private javax.swing.JCheckBox EH1;
    private javax.swing.JCheckBox EI2;
    private javax.swing.JCheckBox GF3;
    private javax.swing.JCheckBox GH1;
    private javax.swing.JCheckBox GI2;
    private javax.swing.JCheckBox HI2;
    private javax.swing.JLabel HoneyI;
    private javax.swing.JCheckBox IF3;
    private javax.swing.JCheckBox LF3;
    private javax.swing.JCheckBox LH1;
    private javax.swing.JCheckBox LI2;
    private javax.swing.JCheckBox LTF3;
    private javax.swing.JCheckBox LTI2;
    private javax.swing.JCheckBox MF3;
    private javax.swing.JCheckBox MH1;
    private javax.swing.JCheckBox MI2;
    private javax.swing.JCheckBox MIF3;
    private javax.swing.JCheckBox MIH1;
    private javax.swing.JCheckBox MII2;
    private javax.swing.JCheckBox MTF3;
    private javax.swing.JCheckBox MTI2;
    private javax.swing.JCheckBox NF3;
    private javax.swing.JCheckBox NH1;
    private javax.swing.JCheckBox NI2;
    private javax.swing.JCheckBox NTF3;
    private javax.swing.JCheckBox NTH1;
    private javax.swing.JCheckBox NTI2;
    private javax.swing.JCheckBox RI2;
    private javax.swing.JCheckBox TF3;
    private javax.swing.JCheckBox TH1;
    private javax.swing.JCheckBox TI2;
    private javax.swing.JLabel Total;
    private javax.swing.JTextPane Zshow;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton re;
    private javax.swing.JScrollPane zxx;
    // End of variables declaration//GEN-END:variables
}
